# Site settings
site_name: Kondo
site_url: https://www.gokondo.io
site_description: "A minimalist blog powered by Kondo."

# Layout settings
layouts:
  main: "main_layout.liquid"  # Layout for the homepage or main pages
  post: "post_layout.liquid"  # Layout for individual blog posts

# Date and timezone settings
date_format: "%B %d, %Y"  # Date format for posts (e.g., "January 1, 2024")
timezone: "UTC"           # Timezone for date formatting

# Social media links (optional, for footer or sidebar)
social:
  twitter: "https://twitter.com/yourusername"
  instagram: "https://instagram.com/yourusername"
  github: "https://github.com/yourusername"

# Analytics (optional)
analytics: "UA-12345678-9"  # Google Analytics tracking ID
